-- Rebuild the tracker table around a UTC instant.
--
-- WHAT WAS WRONG
--
-- `date_time` held LOCAL wall time in a timezone-naive DateTime, with the zone
-- it belonged to in `tzname` beside it. Every country statistic wants exactly
-- that -- getCountryStats, getCountrySessions and getCurrentCountryLength all
-- count `toDate(date_time)`, the local calendar day, which is the only day a
-- "days in country" figure can mean.
--
-- But a local wall clock is not a point in time, and anything that filters a
-- time range needs one. A Grafana panel filters an instant range, and matching
-- it against a wall clock silently drops or admits rows by the current UTC
-- offset -- the "the dashboard says 4 points, the day has 3246" bug of
-- 2026-08-29. The workaround was `scripts/system/tracker-tz.py`, which
-- generates a 27-branch multiIf to be pasted into every panel, and which has
-- to be regenerated by hand after every new country.
--
-- WHAT THIS STORES INSTEAD
--
--     ts         DateTime('UTC')  the instant. The sort key.
--     tz_offset  Int32            seconds east of UTC, at that instant.
--     date_time  ALIAS ts + tz_offset
--
-- `date_time` keeps its name, its type and its exact values, so not one query
-- in this repo changes -- but it is no longer stored. It is arithmetic over
-- two columns, and `tz_offset` is defined as `date_time - ts`, so the identity
-- holds by construction rather than by approximation.
--
-- The offset rather than the zone name is what makes this work. ClickHouse
-- cannot convert a timestamp with a per-row timezone: `toTimeZone(ts, tzname)`
-- with `tzname` as a column fails with Code 44, ILLEGAL_COLUMN, because the
-- timezone argument must be a constant. That single restriction is the entire
-- reason tracker-tz.py exists. An offset needs no constant -- it is addition --
-- so it is correct for a country visited next year without anyone regenerating
-- anything, and it is DST-correct per row: Europe/Podgorica appears in this
-- data at both +1h and +2h, which a per-zone lookup would flatten.
--
-- `tzname` is kept. It is no longer load-bearing for any computation, but it
-- is the only record of WHERE a row was logged, and it costs 10 KB.
--
-- WHY A REBUILD AND NOT AN ALTER
--
-- An ALIAS column cannot be part of the sorting key, and the sorting key
-- cannot be changed in place. Making `date_time` computed therefore requires
-- ORDER BY ts, and that means a new table and a swap. ORDER BY ts is the
-- better key anyway: it is what every dashboard filters, and the statistics
-- scan the whole table either way. `ts` is very nearly sorted the same as
-- `date_time` -- they disagree at 1753 rows out of 1.02M, the moments a flight
-- lands and the local clock jumps.
--
-- THE BACKFILL IS EXACT
--
-- Local -> UTC is ambiguous only inside a DST fall-back hour. Checked against
-- the live table on 2026-09-11: no row falls in a transition hour of any of
-- its 29 zones. Podgorica, Sarajevo, Belgrade, Istanbul and Cairo are the only
-- zones here that have ever observed DST while the bot was logging, and all
-- are empty in those windows. The Android-style `GMT-06:00` names, which
-- ClickHouse does not know, are shifted arithmetically; `GMT`, `Etc/UTC` and
-- the empty tzname are already UTC. 14 distinct offsets result, all whole or
-- half hours.
--
-- The multiIf below is the last use of that generated expression. After this
-- migration nothing needs it again.
--
-- THE SWAP
--
-- The copy takes a snapshot (`WHERE date_time <= max(date_time)`), so pings
-- that land while it runs stay in the old table and are picked up by the
-- top-up after the exchange. The one gap is the instant of the EXCHANGE
-- itself: an old container still serving at that moment inserts `date_time`,
-- which is an ALIAS in the new table, and its insert fails and is logged. That
-- is a few pings of a 30-second cadence during a deploy, on a table where a
-- day holds thousands of them and a country-day needs one.
--
-- The old table is kept as `country_days_tracker_pre_utc`, not dropped, so the
-- three statistics queries can be diffed against it afterwards. Drop it by
-- hand once they match.
--
-- ONE TYPE CHANGE
--
-- `bs` was `LowCardinality(UInt8)` and is now plain `UInt8`. ClickHouse 26
-- refuses to create the former at all (Code 455, SUSPICIOUS_TYPE_FOR_LOW_
-- CARDINALITY) and it is right to: a dictionary plus an index is strictly more
-- work and more bytes than the single byte it wraps. The old table predates
-- that check. The values are unchanged -- `bs` is 0-3 -- and nothing reads the
-- column's type, only its value.
--
-- CODECS
--
-- Carried over from V12, which measured them on this data: Delta + ZSTD(9) on
-- every numeric column, nothing on the LowCardinality ones. `ts` gets the same
-- treatment as `date_time` had and behaves better under it. `tz_offset` is 14
-- distinct values in sort order and compresses to nothing.

CREATE TABLE IF NOT EXISTS country_days_tracker_bot.country_days_tracker_utc
(
    `ts` DateTime('UTC') CODEC(Delta(4), ZSTD(9)),
    `tz_offset` Int32 CODEC(Delta(4), ZSTD(9)),
    `date_time` DateTime ALIAS ts + tz_offset,
    `country` LowCardinality(String),
    `longitude` Float32 DEFAULT 0 CODEC(Delta(4), ZSTD(9)),
    `latitude` Float32 DEFAULT 0 CODEC(Delta(4), ZSTD(9)),
    `tzname` LowCardinality(String),
    `alt` UInt16 CODEC(Delta(2), ZSTD(9)),
    `batt` UInt8,
    `acc` UInt8 CODEC(Delta(1), ZSTD(9)),
    `vac` UInt8 CODEC(Delta(1), ZSTD(9)),
    `conn` LowCardinality(String),
    `locality` LowCardinality(String),
    `ghash` LowCardinality(String),
    `p` Float64 CODEC(Delta(8), ZSTD(9)),
    `addr` LowCardinality(String),
    `bssid` LowCardinality(String),
    `ssid` LowCardinality(String),
    `bs` UInt8 DEFAULT 0 CODEC(ZSTD(9)),
    `vel` UInt16 DEFAULT 0 CODEC(Delta(2), ZSTD(9)),
    `cog` UInt16 DEFAULT 0 CODEC(Delta(2), ZSTD(9)),
    `m` Int8 DEFAULT 0
)
ENGINE = MergeTree
ORDER BY ts
SETTINGS index_granularity = 8192;

INSERT INTO country_days_tracker_bot.country_days_tracker_utc
    (ts, tz_offset, country, longitude, latitude, tzname, alt, batt, acc, vac,
     conn, locality, ghash, p, addr, bssid, ssid, bs, vel, cog, m)
SELECT
    utc AS ts,
    toInt32(dateDiff('second', utc, date_time)) AS tz_offset,
    country, longitude, latitude, tzname, alt, batt, acc, vac,
    conn, locality, ghash, p, addr, bssid, ssid, bs, vel, cog, m
FROM
(
    SELECT
        toTimeZone(
            multiIf(
                tzname = 'Asia/Kuala_Lumpur', toDateTime(toString(date_time), 'Asia/Kuala_Lumpur'),
                tzname = 'Asia/Bangkok', toDateTime(toString(date_time), 'Asia/Bangkok'),
                tzname = 'Asia/Makassar', toDateTime(toString(date_time), 'Asia/Makassar'),
                tzname = 'Asia/Seoul', toDateTime(toString(date_time), 'Asia/Seoul'),
                tzname = 'Asia/Hong_Kong', toDateTime(toString(date_time), 'Asia/Hong_Kong'),
                tzname = 'Indian/Mauritius', toDateTime(toString(date_time), 'Indian/Mauritius'),
                tzname = 'Asia/Almaty', toDateTime(toString(date_time), 'Asia/Almaty'),
                tzname = 'Indian/Maldives', toDateTime(toString(date_time), 'Indian/Maldives'),
                tzname = 'Asia/Muscat', toDateTime(toString(date_time), 'Asia/Muscat'),
                tzname = 'Asia/Colombo', toDateTime(toString(date_time), 'Asia/Colombo'),
                tzname = 'Asia/Dubai', toDateTime(toString(date_time), 'Asia/Dubai'),
                tzname = 'Europe/Podgorica', toDateTime(toString(date_time), 'Europe/Podgorica'),
                tzname = 'Europe/Istanbul', toDateTime(toString(date_time), 'Europe/Istanbul'),
                tzname = 'Europe/Sarajevo', toDateTime(toString(date_time), 'Europe/Sarajevo'),
                tzname = 'GMT-06:00', date_time - toIntervalSecond(-21600),
                tzname = 'GMT-05:00', date_time - toIntervalSecond(-18000),
                tzname = 'Europe/Belgrade', toDateTime(toString(date_time), 'Europe/Belgrade'),
                tzname = 'GMT-07:00', date_time - toIntervalSecond(-25200),
                tzname = 'Asia/Jakarta', toDateTime(toString(date_time), 'Asia/Jakarta'),
                tzname = 'Asia/Shanghai', toDateTime(toString(date_time), 'Asia/Shanghai'),
                tzname = 'Asia/Singapore', toDateTime(toString(date_time), 'Asia/Singapore'),
                tzname = 'Asia/Ho_Chi_Minh', toDateTime(toString(date_time), 'Asia/Ho_Chi_Minh'),
                tzname = 'GMT-08:00', date_time - toIntervalSecond(-28800),
                tzname = 'Africa/Cairo', toDateTime(toString(date_time), 'Africa/Cairo'),
                tzname = 'Asia/Qatar', toDateTime(toString(date_time), 'Asia/Qatar'),
                tzname = 'Asia/Jerusalem', toDateTime(toString(date_time), 'Asia/Jerusalem'),
                date_time),
            'UTC') AS utc,
        *
    FROM country_days_tracker_bot.country_days_tracker
    WHERE date_time <= (SELECT max(date_time) FROM country_days_tracker_bot.country_days_tracker)
);

EXCHANGE TABLES country_days_tracker_bot.country_days_tracker
            AND country_days_tracker_bot.country_days_tracker_utc;

-- After the exchange the names are swapped: `country_days_tracker` is the new
-- table and `country_days_tracker_utc` is the original. This picks up whatever
-- the old container wrote while the copy was running.
INSERT INTO country_days_tracker_bot.country_days_tracker
    (ts, tz_offset, country, longitude, latitude, tzname, alt, batt, acc, vac,
     conn, locality, ghash, p, addr, bssid, ssid, bs, vel, cog, m)
SELECT
    utc AS ts,
    toInt32(dateDiff('second', utc, date_time)) AS tz_offset,
    country, longitude, latitude, tzname, alt, batt, acc, vac,
    conn, locality, ghash, p, addr, bssid, ssid, bs, vel, cog, m
FROM
(
    SELECT
        toTimeZone(
            multiIf(
                tzname = 'Asia/Kuala_Lumpur', toDateTime(toString(date_time), 'Asia/Kuala_Lumpur'),
                tzname = 'Asia/Bangkok', toDateTime(toString(date_time), 'Asia/Bangkok'),
                tzname = 'Asia/Makassar', toDateTime(toString(date_time), 'Asia/Makassar'),
                tzname = 'Asia/Seoul', toDateTime(toString(date_time), 'Asia/Seoul'),
                tzname = 'Asia/Hong_Kong', toDateTime(toString(date_time), 'Asia/Hong_Kong'),
                tzname = 'Indian/Mauritius', toDateTime(toString(date_time), 'Indian/Mauritius'),
                tzname = 'Asia/Almaty', toDateTime(toString(date_time), 'Asia/Almaty'),
                tzname = 'Indian/Maldives', toDateTime(toString(date_time), 'Indian/Maldives'),
                tzname = 'Asia/Muscat', toDateTime(toString(date_time), 'Asia/Muscat'),
                tzname = 'Asia/Colombo', toDateTime(toString(date_time), 'Asia/Colombo'),
                tzname = 'Asia/Dubai', toDateTime(toString(date_time), 'Asia/Dubai'),
                tzname = 'Europe/Podgorica', toDateTime(toString(date_time), 'Europe/Podgorica'),
                tzname = 'Europe/Istanbul', toDateTime(toString(date_time), 'Europe/Istanbul'),
                tzname = 'Europe/Sarajevo', toDateTime(toString(date_time), 'Europe/Sarajevo'),
                tzname = 'GMT-06:00', date_time - toIntervalSecond(-21600),
                tzname = 'GMT-05:00', date_time - toIntervalSecond(-18000),
                tzname = 'Europe/Belgrade', toDateTime(toString(date_time), 'Europe/Belgrade'),
                tzname = 'GMT-07:00', date_time - toIntervalSecond(-25200),
                tzname = 'Asia/Jakarta', toDateTime(toString(date_time), 'Asia/Jakarta'),
                tzname = 'Asia/Shanghai', toDateTime(toString(date_time), 'Asia/Shanghai'),
                tzname = 'Asia/Singapore', toDateTime(toString(date_time), 'Asia/Singapore'),
                tzname = 'Asia/Ho_Chi_Minh', toDateTime(toString(date_time), 'Asia/Ho_Chi_Minh'),
                tzname = 'GMT-08:00', date_time - toIntervalSecond(-28800),
                tzname = 'Africa/Cairo', toDateTime(toString(date_time), 'Africa/Cairo'),
                tzname = 'Asia/Qatar', toDateTime(toString(date_time), 'Asia/Qatar'),
                tzname = 'Asia/Jerusalem', toDateTime(toString(date_time), 'Asia/Jerusalem'),
                date_time),
            'UTC') AS utc,
        *
    FROM country_days_tracker_bot.country_days_tracker_utc
)
WHERE utc > (SELECT max(ts) FROM country_days_tracker_bot.country_days_tracker);

RENAME TABLE country_days_tracker_bot.country_days_tracker_utc
          TO country_days_tracker_bot.country_days_tracker_pre_utc;
